# Generated by Django 3.0b1 on 2019-11-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
