# Generated by Django 3.0b1 on 2019-11-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0002_tool_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolbox',
            options={'verbose_name': 'Tool Box', 'verbose_name_plural': 'Tool Boxes'},
        ),
    ]
