# Generated by Django 3.0b1 on 2019-11-16 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0003_auto_20191116_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='pub_date',
        ),
    ]
