# Generated by Django 3.0b1 on 2019-11-19 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toolbox', '0005_auto_20191116_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolbox',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toolbox', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='toolbox',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
