# Generated by Django 3.0b1 on 2019-11-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0006_auto_20191118_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolbox',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
